### ISSUE TITLE
will this work with api TOKENs ?

### ISSUE THREAD

**Issue by thebigboss84** [GearPlug/hubspot-python#3]
thanks for the wrapper ! , seems simple and easy to use ! but I wonder if this will work with access tokens ?

**Comment by ingmferrer** [comment]
You would need to instantiate the client and then set the access token 

https://github.com/GearPlug/hubspot-python/blob/c5b56e3214338f5f1fa4263c50e871c2eec6a1fa/hubspot/client.py#L61

Feel free to re open this issue if you still have issues.
